### ISSUE TITLE
not running on h2 with documented command line

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#111]
I tried to run the app on H2, following the [master README](https://github.com/mix-it/cesar#launch-the-webapp) and [`common` README](https://github.com/mix-it/cesar/tree/master/common#database-used-when-you-launch-the-app), with the following command: `./gradlew bootRun --spring.datasource.driver-class-name=org.h2.Driver --spring.datasource.url=jdbc:h2:file:cesar --spring.datasource.username=sa --spring.datasource.password=`

But that is failing :
```
➜  cesar git:(master) ./gradlew bootRun --spring.datasource.driver-class-name=org.h2.Driver --spring.datasource.url=jdbc:h2:file:cesar --spring.datasource.username=sa --spring.datasource.password=

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :server:bootRun from command line.
> Unknown command-line option '--spring.datasource.driver-class-name'.

* Try:
Run gradlew help --task :server:bootRun to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.248 secs
```

**Comment by javamind** [comment]
Your database is not automatically generated. You have to create it with flyway or you can add properties in your command line
``` 
--spring.jpa.hibernate.ddl-auto=create
--spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
```

**Comment by javamind** [comment]
Are you OK with this doc ?
