### ISSUE TITLE
OAuth: Google+ authentication not working on RCT env

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#117]
When using an oAuth authentication on RCT environment (http://cesar.cfapps.io), redirection after account selection does not work :
![image](https://cloud.githubusercontent.com/assets/750715/11360953/766d05fa-9289-11e5-9f05-b6687f4977f2.png)

The URL is
`https://accounts.google.com/o/oauth2/auth?scope=openid&response_type=code&redirect_uri=http%3A%2F%2Fcesar.cfapps.io%2F%2Fapp%2Foauth%2Fgoogle&state=E65927A2BF4797913CE025795CF8DB&client_id=577472768734-jj9gtn3vbpgh502ht1fe6omb8b5hpioq.apps.googleusercontent.com&hl=en&from_login=1&as=2e8262b17518f75a&authuser=0`.
Note the double-slash in the asked redirect URL : http://cesar.cfapps.io//app/oauth/google

**Comment by javamind** [comment]
Pb is solved => env variable error
