### ISSUE TITLE
Registration with password: does not work

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#119]
I tried to register with a password. It keeps saying "Ce login n'existe pas. Veuillez créer un compte pour vous connecter" :
![image](https://cloud.githubusercontent.com/assets/750715/11361074/a8c60e2e-928a-11e5-9fc1-2c1875b750ab.png)

That tells:
* registration with password is broken
* "clacote" is my username on previous Mix-IT website. So either sign-in is broken (it didn't find my username is DB), or DB data had not been injected in RCT DB.

**Comment by javamind** [comment]
Account data won't be injected in the new website. If you want to link an account with your email, you need to create an account with password, google+ or twitter and send us your email adress. If this adress exist in the members, your old profile will be attached to your new account

**Comment by javamind** [comment]
@clacote ?

**Comment by clacote** [comment]
Registering via Twitter works.
