### ISSUE TITLE
/account page does not exist, without 404 error.

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#120]
When logged in, an "account" menu is shown: 
![image](https://cloud.githubusercontent.com/assets/750715/11361141/5cbc6ab8-928b-11e5-9b00-48c91aa1e98a.png)

But this link opens nothing (does not navigate). Typing http://cesar.cfapps.io/account URL in browser opens a new page, empty, without 404:
![image](https://cloud.githubusercontent.com/assets/750715/11361156/9c4ad908-928b-11e5-9d90-9b43e42c5855.png)

**Comment by javamind** [comment]
There was an error with the minification and ngInject
