### ISSUE TITLE
Bug in sponsor display

### ISSUE THREAD

**Issue by acrepet** [mix-it/cesar#132]
![screenshot_2015-12-01-05-54-48](https://cloud.githubusercontent.com/assets/544206/11492662/82cde064-97f0-11e5-867e-22f1c184e4aa.png)
The logos of the sponsors are not displayed! Otherwise, their name followed by à weird number!

**Comment by javamind** [comment]
For the logos, it's the same thing than the last version
Logo are only displayed in the current sponsor screen
I will delete the level and the id

**Comment by javamind** [comment]
Done logo are now displayed
![image](https://cloud.githubusercontent.com/assets/1812822/11500906/7fc022d4-9830-11e5-96b7-ec44f7fee2ed.png)
