### ISSUE TITLE
Staff page not up-to-date

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#152]
I'm a staff member. I registrered via Twitter, and found that my bio was pre-filled with previous mix-it.fr data (great!).
I edited my profile to update my bio :
![image](https://cloud.githubusercontent.com/assets/750715/11875377/9b0718f2-a4e4-11e5-8338-47ee1e8ce6a9.png)

But the staff page stills display my obsolete bio:
![image](https://cloud.githubusercontent.com/assets/750715/11875425/d317c8ae-a4e4-11e5-930f-04436cd76462.png)

Is this a bug? Wrongly duplicated profile data? A cache on staff page?

**Comment by javamind** [comment]
There's a cache on all the members info
hum I need to update te cache after an update

**Comment by javamind** [comment]
see #163
