### ISSUE TITLE
Création de comptes annulée - menu bloqué

### ISSUE THREAD

**Issue by k33g** [mix-it/cesar#159]
Procédure
- login (menu clé)
- sélection twitter
- j'arrive sur "Création d'un compte" (http://cesar.cfapps.io/createaccountsocial)
- je veux annuler (par exemple utiliser le menu sponsor)
-> je reste bloquer sur la même page

mais le back fonctionne

**Comment by javamind** [comment]
C'est une fonctionnalité remontée par @clacote 
Le but est de te forcer à mettre un email car c'est notre seul moyen de te contacter. On pourrait le faire via les providers Oauth mais perso j'ai horreur de voir qu'un site veut me soutirer mes infos d'identification. Au moins là on est transparent dans ce qu'on utilise

**Comment by k33g** [comment]
OK
