### ISSUE TITLE
CFP: connexion via twitter

### ISSUE THREAD

**Issue by k33g** [mix-it/cesar#173]
lors de la connexion via twitter après click sur le lien CFP je suis redirigé sur la home et pas sur le CFP

**Comment by javamind** [comment]
Oui car j'avais une merde pour stocker le redirect dans la request. En gros quand tu reviens de Twitter tu ne sais pas sur quelle page retournée. Compliqué de ne pas faire du state full

**Comment by javamind** [comment]
see #178

**Comment by k33g** [comment]
localstorage peut-être

**Comment by javamind** [comment]
C'est le serveur qui fait l'appel. Il faut que je trouve un truc. Ce sera
par contre pas pour la version de jeudi car il faut que je bosse un peu mon
talk


2016-01-17 22:43 GMT+01:00 Philippe CHARRIERE <notifications@github.com>:

> localstorage peut-être
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mix-it/cesar/issues/173#issuecomment-172386055>.
>



-- 
*Guillaume EHRET*
*Conseil et développement*
*https://www.dev-mind.fr/* <http://www.dev-mind.fr/>
