### ISSUE TITLE
CFP: enregistrement impossible

### ISSUE THREAD

**Issue by k33g** [mix-it/cesar#175]
Lorsque j'essaye d'enregistrer j'ai un message d'erreur sans détail:

    Erreur détectée. Veuillez réessayer ou contacter l'équipe Mix-IT pour nous remonter ce bug

Il me semble pourtant avoir tout saisi (peut être utiliser la validation angular sur les champs de saisie ou afficher un message détaillé pour comprendre d'où vient l'erreur)

**Comment by javamind** [comment]
It was a problem in database installation
