### ISSUE TITLE
We can't add an interest when the session is submited

### ISSUE THREAD

**Issue by javamind** [mix-it/cesar#196]

**Comment by benzonico** [comment]
On va le faire façon github alors : +1

**Comment by javamind** [comment]
Pas besoin de voter on corrige tout si on a la bande passante. C'est corrigé. Un petit problème de cache à un endroit où on n'en voulait pas. On essayait d'enregistrer des entités non attachées à la session Hibernate... C'est cool ça montre qu'il y a des gens qui ont des intérêts communs :-)

**Comment by javamind** [comment]
Mise en prod ce soir

**Comment by benzonico** [comment]
C'est surtout pour pouvoir suivre que je "vote" :) 
Ok je mettrais les interets ce soir. 
Au passage, on peut modifier l'interet Sonar en SonarQube ?

**Comment by javamind** [comment]
Tu me demandes de corrompre la base de données là :-)
