### ISSUE TITLE
Provide a 404 error page

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/cesar#207]
Currently going to a page that does not exists (like https://www.mix-it.fr/foobar) return Spring Boot default whitelabel page. A proper 404 page should be returned.

**Comment by javamind** [comment]
I can't reproduce. If you use a bad URL you are redirected on homepage (Angular router behavior)
In Spring config I used 
```java
 @Bean
    public EmbeddedServletContainerCustomizer containerCustomizer() {

        return (container -> {
            container.addErrorPages(new ErrorPage(HttpStatus.NOT_FOUND, "/cerror/404"));
        });
    }
```

**Comment by sdeleuze** [comment]
Hum, its works now but I am sure it did not when I tested.
