### ISSUE TITLE
Home: previous speakers avatars are very pixelated

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#208]
On Home, previous speakers' avatars pictures are of poor quality, very pixelated:
![image](https://cloud.githubusercontent.com/assets/750715/12776541/0a0abb9a-ca57-11e5-938a-9158a6f98ad3.png)

It looks that static assets are served by the website (like http://www.mix-it.fr/img/speakers/fox.jpeg)
Gravatar should be used (speakers emails used to retrieve gravatars were stored in previous DB).

**Comment by clacote** [comment]
It's strange that you didn't use a gravatar directive, like [there is tons of](https://www.google.fr?q=angular%20gravatar). You'll need to display a gravatar for every member.

**Comment by javamind** [comment]
You are right but this part will of the site will disappear soon when the 2016 speakers will be known. But I am a purist I will create a directive
