### ISSUE TITLE
Speaker page : Organize sessions by event

### ISSUE THREAD

**Issue by mfillon** [mix-it/cesar#283]
On a speaker page (`/member/speaker/<id>`), il's not clear which session belongs to which event.

As a speaker may come back for different edition of the event, we should see clearly if the session is from a previous edition or from the next one. 

For instance, [this (great) speaker](https://www.mix-it.fr/member/speaker/597), came for previous edition of Mix-IT and (I guess) is coming for the next one.

And the latest session should appear first.

**Comment by javamind** [comment]
We choose to not display old sessions for a speaker. We can find them on the old edition pages. It's better to avoid confusion
