### ISSUE TITLE
Code of Conduct: only French version linked, with bad HTTPS support

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#289]
The page https://www.mix-it.fr/conduite always links to https://confcodeofconduct.com/index-fr.html, even in English. In English, http://confcodeofconduct.com/index.html should be linked.

Also, if the link displays an **http** version, link points to http**s** version, which is not supported : see https://confcodeofconduct.com/index-fr.html

Only http://confcodeofconduct.com/index-fr.html (no https) and http://confcodeofconduct.com/index.html should be used.

**Comment by clacote** [comment]
This is urgent: that will be used by an american speaker with travel expenses, and he needs to justify to his employer that the conference is clean.

**Comment by mpetitdant** [comment]
Urgent lik to do now or to be done by the week-end ?

**Comment by clacote** [comment]
like by the week-end, I guess. I can even try to do it blindly this evening during commute.
