### ISSUE TITLE
Sponsors, partners: add mention to LyonTechHub

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#293]
http://www.lyontechhub.org/

**Comment by clacote** [comment]
I'll try to find their logo source.

**Comment by clacote** [comment]
LyonTechHub logos: https://github.com/lyontechhub/lyontechhub.github.io/tree/dev/imgs/logo
(@javamind: you'll be happy, there is a SVG! :p)

**Comment by javamind** [comment]
Cool
