### ISSUE TITLE
Mettre en place le chargement différé des images

### ISSUE THREAD

**Issue by javamind** [mix-it/cesar#77]
Il existe une directive Angular qui le fait et ceci permet de commencer à afficher le site même si le site n'est pas fini de charger. L'utiliser sur la home notamment pour tout ce qui est affiché dans un second temps. Les images du bas de page ne sont visibles que lorsque l'utilisateur scrolle

**Comment by clacote** [comment]
C'est le fonctionnement normal d'un navigateur qui affiche du HTML: pour chaque ressource statique (dont les images), il lance une requète asynchrone. Normalement, sauf à faire du CSS chelou (un terme technique pour tout ce à quoi je ne comprends rien) qui ferait que le layout dépend de l'image et de sa taille, le moteur de rendu est capable d'afficher la page sans les images qui se chargeront par la suite.

**Comment by javamind** [comment]
Oui mais il n'y a pas d'animation. C'est pour ça qu'une directive peut être sympa
