### ISSUE TITLE
Material CSS : menu on iPhone never closes

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#85]
Once you opened the collapsed responsive menu on a (i)phone, you can't close it, even when navigating to another page

**Comment by javamind** [comment]
Is it possible to know if there are Javascript errors ?

**Comment by clacote** [comment]
When opening https://cesar.cfapps.io:
> [Warning] Invalid CSS property declaration at: * (www-embed-player-sprite-mode-2x-vfl7yvP23.css, line 1)
> [Warning] Invalid CSS property declaration at: * (www-embed-player-sprite-mode-2x-vfl7yvP23.css, line 1)
> [Info] Content blocker prevented frame displaying https://cesar.cfapps.io/home from loading a resource from https://static.doubleclick.net/instream/ad_status.js (www-embed-player.js, line 28)

When opening the navbar by clicking on the hamburger icon: **no JS errors**

The issue is still there, though:
![img_0804](https://cloud.githubusercontent.com/assets/750715/11118724/6388ff32-8944-11e5-86de-09d1cd21c9dc.jpg)

**Comment by clacote** [comment]
For your information, we have the exact same issue on a Ninja Squad Angular application using the (same?) Material CSS framework.

**Comment by javamind** [comment]
I think we need to use the last version https://github.com/google/material-design-lite/releases/tag/v1.0.6. This version has several fix for IOS9

**Comment by clacote** [comment]
#98 didn't fix it.

**Comment by acrepet** [comment]
I have the same problem with Android
