### ISSUE TITLE
Cannot import project with IntelliJ Idea 15

### ISSUE THREAD

**Issue by clacote** [mix-it/cesar#95]
When importing Gradle project into IntelliJ Idea 15 (using Gradle Wrapper) there is a blocking error:
![image](https://cloud.githubusercontent.com/assets/750715/11112714/248dae28-8916-11e5-8af5-d0ecfc298c74.png)

Unfortunately, link to log in this popup doesn't open anything.

**Comment by k33g** [comment]
with my own Gradle install (so without wrapper), it's ok with IntelliJ Community 15

**Comment by clacote** [comment]
Same problem without Gradle Wrapper but my own local Gradle 2.4.
I'm using IntelliJ 15 Utlimate, though.

**Comment by clacote** [comment]
I'm no expert in Gradle, but the exception `DefaultModuleComponentSelector` sounds like IntelliJ can't find the default gradle sub-module, if there is such a thing in a Gradle project.

**Comment by k33g** [comment]
Gradle 2.2.1, I will upgrade and make more tests

**Comment by clacote** [comment]
Don't know why (latest IntelliJ patch?), but import is now fine.
